# Generated by Django 5.2.6 on 2025-09-28 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_petcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petcomment',
            old_name='creat_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='petcomment',
            name='comment_text',
        ),
        migrations.AddField(
            model_name='petcomment',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
