# Generated by Django 5.2.6 on 2025-09-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_creat_at_petcomment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petcomment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='petcomment',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterModelTable(
            name='petcomment',
            table='core_petcomment',
        ),
    ]
