# Generated by Django 5.2.6 on 2025-09-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('animal_type', models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кошка'), ('bird', 'Птица'), ('fish', 'Рыба'), ('other', 'Другое')], max_length=20, verbose_name='Тип животного')),
                ('breed', models.CharField(max_length=100, verbose_name='Порода')),
                ('family', models.CharField(max_length=100, verbose_name='Семейство')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст (в месяцах)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('hypoallergenic', models.BooleanField(default=False, verbose_name='Гипоаллергенный')),
                ('feeding_type', models.TextField(blank=True, verbose_name='Рацион питания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
    ]
