# Generated by Django 5.2.6 on 2025-09-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Питомник', 'verbose_name_plural': 'Питомники'},
        ),
        migrations.AlterModelTable(
            name='pet',
            table='nursery_pet',
        ),
    ]
