# Generated by Django 5.2.6 on 2025-10-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0003_pet_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.AddField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
