# Generated by Django 5.2.6 on 2025-10-06 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0004_remove_pet_age_pet_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedigree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother', models.CharField(blank=True, max_length=100, null=True, verbose_name='Мать')),
                ('father', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отец')),
                ('generation', models.PositiveIntegerField(default=1, verbose_name='Поколение')),
                ('breeding_date', models.DateField(blank=True, null=True, verbose_name='Дата разведения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedigree', to='nursery.pet')),
            ],
        ),
    ]
