# Generated by Django 5.2.6 on 2025-10-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0005_pedigree'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата деактивации'),
        ),
    ]
