# Generated by Django 5.2.6 on 2025-10-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0006_pet_deactivated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
